### ISSUE TITLE
error json load "user"

### ISSUE THREAD

**Issue by androidEl** [akasakaid/tomarketod#15]
saya sudah isi data.txt tapi saat running error seperti ini

`        
[2024-09-02 03:58:37] total account : 1
[2024-09-02 03:58:37] total proxies detected : 0
[2024-09-02 03:58:37] use proxy : False
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/workspaces/tomarketod/bot.py", line 342, in <module>
    app.main()
  File "/workspaces/tomarketod/bot.py", line 310, in main
    user = json.loads(parser["user"])
                      ~~~~~~^^^^^^^^
KeyError: 'user'`

**Comment by bayyesterday** [comment]
same

**Comment by akasakaid** [comment]
The query data you entered is incorrect.

**Comment by akasakaid** [comment]
The query data you entered is incorrect.
