### ISSUE TITLE
claim error

### ISSUE THREAD

**Issue by supmyhava** [akasakaid/tomarketod#16]
[2024-09-02 05:51:05] account number : 2/3
[2024-09-02 05:51:05] name : 33
[2024-09-02 05:51:05] balance : 837407
Traceback (most recent call last):
  File "/root/tomarketod/bot.py", line 342, in <module>
    app.main()
  File "/root/tomarketod/bot.py", line 329, in main
    result = self.get_balance()
             ^^^^^^^^^^^^^^^^^^
  File "/root/tomarketod/bot.py", line 181, in get_balance
    self.end_farming()
  File "/root/tomarketod/bot.py", line 98, in end_farming
    poin = res.json()["data"]["claim_this_time"]
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'claim_this_time'

**Comment by akasakaid** [comment]
> [2024-09-02 05:51:05] account number : 2/3
> [2024-09-02 05:51:05] name : 33
> [2024-09-02 05:51:05] balance : 837407
> Traceback (most recent call last):
>   File "/root/tomarketod/bot.py", line 342, in <module>
>     app.main()
>   File "/root/tomarketod/bot.py", line 329, in main
>     result = self.get_balance()
>              ^^^^^^^^^^^^^^^^^^
>   File "/root/tomarketod/bot.py", line 181, in get_balance
>     self.end_farming()
>   File "/root/tomarketod/bot.py", line 98, in end_farming
>     poin = res.json()["data"]["claim_this_time"]
>            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
> KeyError: 'claim_this_time'
> 

I'll check it later.
