### ISSUE TITLE
tokens.txt or tokens.json?

### ISSUE THREAD

**Issue by skypeleft** [akasakaid/tomarketod#2]
tokens.txt or tokens.json?
or data.txt??

**Comment by akasakaid** [comment]
data.txt. See [readme](https://github.com/akasakaid/tomarketod?tab=readme-ov-file#how-to-get-data) how to get data.

**Comment by reysilvano78** [comment]
> data.txt. See [readme](https://github.com/akasakaid/tomarketod?tab=readme-ov-file#how-to-get-data) how to get data.

Traceback (most recent call last):                                  File "/storage/emulated/0/bot/tomarketod/bot.py", line 323, in <module>
    app.main()
  File "/storage/emulated/0/bot/tomarketod/bot.py", line 299, in main
    token = self.login(data)
            ^^^^^^^^^^^^^^^^                                        File "/storage/emulated/0/bot/tomarketod/bot.py", line 63, in login
    token = res.json()["data"]["access_token"]                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^                    KeyError: 'access_token'

**Comment by akasakaid** [comment]
> > data.txt. See [readme](https://github.com/akasakaid/tomarketod?tab=readme-ov-file#how-to-get-data) how to get data.
> 
> Traceback (most recent call last):                                  File "/storage/emulated/0/bot/tomarketod/bot.py", line 323, in <module>
>     app.main()
>   File "/storage/emulated/0/bot/tomarketod/bot.py", line 299, in main
>     token = self.login(data)
>             ^^^^^^^^^^^^^^^^                                        File "/storage/emulated/0/bot/tomarketod/bot.py", line 63, in login
>     token = res.json()["data"]["access_token"]                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^                    KeyError: 'access_token'

Your data is wrong

**Comment by alparo** [comment]
The user data should be fresh. Try to get it again and store to the data.txt.
