### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by d0tf** [akasakaid/tomarketod#3]
How to fix this? 
- Python version:
`Python 3.10.6` and `Python 3.11.2`
- Operating System:
Windows and Ubuntu
```sh
Traceback (most recent call last):
  File "X:\xxx\xxx\tomarketod\bot.py", line 324, in <module>
    app.main()
  File "X:\xxx\xxx\tomarketod\bot.py", line 311, in main
    result = self.get_balance()
  File "X:\xxx\xxx\tomarketod\bot.py", line 155, in get_balance
    self.daily_claim()
  File "X:\xxx\xxx\tomarketod\bot.py", line 102, in daily_claim
    poin = data["today_points"]
TypeError: string indices must be integers
```

**Comment by akasakaid** [comment]
I already fix it, `git pull` to get update !

**Comment by d0tf** [comment]
Thanks, it works now
